// Catecismo para Niños — Preguntas 1–145
// Versión en español de la tradición reformada presbiteriana (Children's Catechism)
const CATECISMO = {
  1:  { p: '¿Quién te hizo?', r: 'Dios.' },
  2:  { p: '¿Qué más hizo Dios?', r: 'Dios hizo todas las cosas.' },
  3:  { p: '¿Por qué te hizo Dios a ti y a todas las cosas?', r: 'Para su propia gloria.' },
  4:  { p: '¿Cómo podemos glorificar a Dios?', r: 'Amándole y obedeciendo sus mandamientos.' },
  5:  { p: '¿Por qué debemos amar a Dios?', r: 'Porque Él nos hizo y cuida de nosotros.' },
  6:  { p: '¿Hay más de un solo Dios?', r: 'No; solo hay un Dios verdadero.' },
  7:  { p: '¿En cuántas personas subsiste este único Dios?', r: 'En tres personas.' },
  8:  { p: '¿Cuáles son estas tres personas?', r: 'El Padre, el Hijo y el Espíritu Santo.' },
  9:  { p: '¿Qué es Dios?', r: 'Dios es un Espíritu, infinito, eterno e inmutable.' },
  10: { p: '¿Tiene Dios un cuerpo como los hombres?', r: 'No; Dios no tiene cuerpo.' },
  11: { p: '¿Puedes ver a Dios?', r: 'No; yo no puedo ver a Dios, pero Él siempre me ve a mí.' },
  12: { p: '¿Sabe Dios todas las cosas?', r: 'Sí; nada puede ocultarse a Dios.' },
  13: { p: '¿Puede Dios hacer todas las cosas?', r: 'Sí; Dios puede hacer toda su santa voluntad.' },
  14: { p: '¿Dónde aprendes a amar y obedecer a Dios?', r: 'En la Biblia solamente.' },
  15: { p: '¿Quién escribió la Biblia?', r: 'Hombres santos que fueron enseñados por el Espíritu Santo.' },
  16: { p: '¿Quiénes fueron nuestros primeros padres?', r: 'Adán y Eva.' },
  17: { p: '¿De qué fueron hechos nuestros primeros padres?', r: 'Dios formó el cuerpo de Adán del polvo de la tierra, y formó a Eva del cuerpo de Adán.' },
  18: { p: '¿Qué más les dio Dios además de cuerpos?', r: 'Les dio almas que nunca pueden morir.' },
  19: { p: '¿Tienes tú también un alma además de un cuerpo?', r: 'Sí; tengo un alma que nunca puede morir.' },
  20: { p: '¿Cómo sabes que tienes un alma?', r: 'Porque la Biblia me lo dice.' },
  21: { p: '¿En qué condición hizo Dios a Adán y Eva?', r: 'Los hizo santos y felices.' },
  22: { p: '¿Qué es un pacto?', r: 'Un acuerdo entre dos o más personas.' },
  23: { p: '¿Qué pacto hizo Dios con Adán?', r: 'El pacto de obras.' },
  24: { p: '¿Qué debía hacer Adán en el pacto de obras?', r: 'Obedecer a Dios perfectamente.' },
  25: { p: '¿Qué prometió Dios en el pacto de obras?', r: 'Recompensar a Adán con vida si le obedecía.' },
  26: { p: '¿Qué amenazó Dios en el pacto de obras?', r: 'Castigar a Adán con la muerte si desobedecía.' },
  27: { p: '¿Cumplió Adán el pacto de obras?', r: 'No; pecó contra Dios.' },
  28: { p: '¿Qué es el pecado?', r: 'El pecado es cualquier falta de conformidad con la ley de Dios, o transgresión de ella.' },
  29: { p: '¿Cuál fue el pecado de nuestros primeros padres?', r: 'Comer el fruto prohibido.' },
  30: { p: '¿Quién tentó a nuestros primeros padres a pecar?', r: 'El diablo tentó a Eva, y ella y Adán pecaron.' },
  31: { p: '¿En qué estado quedaron Adán y Eva por el pecado?', r: 'Cayeron de la santidad y la felicidad a un estado de pecado y miseria.' },
  32: { p: '¿Cayeron solo ellos en ese estado miserable?', r: 'No; porque todos hemos pecado en Adán.' },
  33: { p: '¿A qué estado cayeron todos los hombres con Adán?', r: 'A un estado de pecado y miseria.' },
  34: { p: '¿Qué es el pecado original?', r: 'El pecado en que todos los hombres nacen por haber pecado en Adán.' },
  35: { p: '¿Cuál es la pena del pecado?', r: 'La muerte y la ira de Dios tanto en esta vida como en la venidera.' },
  36: { p: '¿Puede alguien salvarse por sus propias obras?', r: 'No; nadie puede salvarse por sus propias obras.' },
  37: { p: '¿Qué debes hacer para ser salvo?', r: 'Arrepentirme del pecado y creer en el Señor Jesucristo.' },
  38: { p: '¿Quién es Jesucristo?', r: 'El eterno Hijo de Dios, quien se hizo hombre para salvarnos.' },
  39: { p: '¿Hay algún otro nombre bajo el cielo por el cual podamos ser salvos?', r: 'No; solo el nombre de Jesucristo.' },
  40: { p: '¿Cómo se hizo Cristo semejante a nosotros?', r: 'Cristo, siendo Dios, tomó sobre sí una naturaleza humana.' },
  41: { p: '¿Tuvo Cristo alguna vez pecado?', r: 'No; Él fue perfectamente santo e inocente.' },
  42: { p: '¿Por qué fue necesario que Cristo fuera hombre?', r: 'Para poder obedecer la ley y sufrir y morir en nuestro lugar.' },
  43: { p: '¿Por qué fue necesario que Cristo fuera también Dios?', r: 'Para que su obediencia y sufrimiento fueran de valor infinito y suficiente para nuestra redención.' },
  44: { p: '¿Qué hizo Cristo para salvarnos?', r: 'Vivió una vida perfecta, murió en la cruz y resucitó de entre los muertos.' },
  45: { p: '¿Qué es la expiación?', r: 'Es la satisfacción que Cristo hizo a la justicia de Dios por nuestros pecados.' },
  46: { p: '¿A quiénes beneficia la expiación de Cristo?', r: 'A todos los que de corazón creen en Él.' },
  47: { p: '¿Qué sucedió con Cristo después de su muerte?', r: 'Resucitó de entre los muertos al tercer día.' },
  48: { p: '¿Dónde está Cristo ahora?', r: 'Está sentado a la diestra de Dios Padre en el cielo.' },
  49: { p: '¿Volverá Cristo?', r: 'Sí; vendrá de nuevo a juzgar a los vivos y a los muertos.' },
  50: { p: '¿Qué es creer en el Señor Jesucristo?', r: 'Es depositar toda mi confianza solo en Jesucristo para salvación.' },
  51: { p: '¿Qué es el arrepentimiento?', r: 'Es abandonar mis pecados y volverme a Dios con todo el corazón.' },
  52: { p: '¿Cómo puedes creer en Cristo y arrepentirte?', r: 'Solo por el don del Espíritu Santo.' },
  53: { p: '¿Cómo obra el Espíritu Santo para salvarnos?', r: 'Convence de pecado, ilumina la mente, renueva el corazón y nos da fe para confiar en Cristo.' },
  54: { p: '¿Qué es la regeneración?', r: 'Es la obra del Espíritu Santo que da nueva vida al pecador.' },
  55: { p: '¿Puede alguien entrar al reino de Dios sin nacer de nuevo?', r: 'No; "el que no naciere de nuevo, no puede ver el reino de Dios."' },
  56: { p: '¿Cuáles son los beneficios que reciben en esta vida los que creen en Cristo?', r: 'Justificación, adopción y santificación.' },
  57: { p: '¿Qué es la justificación?', r: 'Es el acto de Dios por el cual perdona todos mis pecados y me declara justo a causa de la obediencia de Cristo.' },
  58: { p: '¿Qué es la adopción?', r: 'Es el acto de Dios por el cual me hace su hijo y heredero juntamente con Cristo.' },
  59: { p: '¿Qué es la santificación?', r: 'Es la obra de Dios por la cual me hace cada vez más puro y santo en toda la vida.' },
  60: { p: '¿Puedes ser perfectamente santo en esta vida?', r: 'No; aún tengo que luchar contra el pecado que mora en mí.' },
  61: { p: '¿Qué les sucede a las almas de los creyentes al morir?', r: 'Pasan a ser perfectamente santas y están con Cristo en el cielo.' },
  62: { p: '¿Qué les sucede a los cuerpos de los creyentes al morir?', r: 'Vuelven al polvo, pero serán resucitados el último día.' },
  63: { p: '¿Qué les sucede a las almas de los que no creyeron al morir?', r: 'Van al infierno, a un estado de tormento eterno.' },
  64: { p: '¿Habrá resurrección de los muertos?', r: 'Sí; habrá resurrección tanto de justos como de injustos.' },
  65: { p: '¿Qué viene después de la resurrección?', r: 'El juicio final.' },
  66: { p: '¿Quién juzgará a los vivos y a los muertos?', r: 'El Señor Jesucristo.' },
  67: { p: '¿Qué les sucede a los condenados en el juicio?', r: 'Son enviados al castigo eterno, separados de Dios para siempre.' },
  68: { p: '¿Qué les sucede a los justos en el juicio?', r: 'Son recibidos en la vida eterna y gozan de Dios para siempre.' },
  69: { p: '¿Qué es la vida eterna?', r: 'Es el gozo para siempre en la presencia de Dios, en el cielo nuevo y la tierra nueva.' },
  70: { p: '¿Cuáles son los medios de gracia?', r: 'La Palabra de Dios, los sacramentos y la oración.' },
  71: { p: '¿Cómo se convierte la Palabra en medio de salvación?', r: 'Cuando la oímos, la leemos y meditamos en ella con fe y oración.' },
  72: { p: '¿Cuáles son los sacramentos del Nuevo Testamento?', r: 'El bautismo y la Cena del Señor.' },
  73: { p: '¿Qué es el bautismo?', r: 'Es un sacramento en el cual el lavamiento con agua en el nombre del Padre, del Hijo y del Espíritu Santo, es señal y sello de que somos del pueblo de Dios.' },
  74: { p: '¿Quiénes deben recibir el bautismo?', r: 'Los creyentes y sus hijos.' },
  75: { p: '¿Qué es la Cena del Señor?', r: 'Es un sacramento en el cual el comer pan y beber vino recuerda y proclama la muerte de Cristo.' },
  76: { p: '¿Para qué instituyó Cristo la Cena del Señor?', r: 'Para recordar su sacrificio y proclamar su muerte hasta que Él venga.' },
  77: { p: '¿Qué es la oración?', r: 'Es hablar con Dios.' },
  78: { p: '¿A quién debemos orar?', r: 'Solo a Dios.' },
  79: { p: '¿En nombre de quién debemos orar?', r: 'En el nombre de Jesucristo.' },
  80: { p: '¿Qué oración nos enseñó Cristo?', r: 'El Padre Nuestro.' },
  81: { p: '¿Cuántas peticiones tiene el Padre Nuestro?', r: 'Seis peticiones.' },
  82: { p: '¿Cuál es la primera petición?', r: '"Santificado sea tu nombre."' },
  83: { p: '¿Qué pedimos en la primera petición?', r: 'Que Dios sea glorificado en todas las cosas.' },
  84: { p: '¿Cuál es la segunda petición?', r: '"Venga tu reino."' },
  85: { p: '¿Qué pedimos en la segunda petición?', r: 'Que el reino de gracia se extienda y venga pronto el reino de gloria.' },
  86: { p: '¿Cuál es la tercera petición?', r: '"Hágase tu voluntad, así en la tierra como en el cielo."' },
  87: { p: '¿Qué pedimos en la tercera petición?', r: 'Que podamos obedecer a Dios en todo, como los ángeles en el cielo.' },
  88: { p: '¿Cuál es la cuarta petición?', r: '"Danos hoy nuestro pan de cada día."' },
  89: { p: '¿Qué pedimos en la cuarta petición?', r: 'Las cosas necesarias para el cuerpo y para la vida.' },
  90: { p: '¿Cuál es la quinta petición?', r: '"Perdónanos nuestras deudas, así como nosotros perdonamos a nuestros deudores."' },
  91: { p: '¿Qué pedimos en la quinta petición?', r: 'Que Dios perdone nuestros pecados, como nosotros perdonamos a quienes nos ofenden.' },
  92: { p: '¿Cuál es la sexta petición?', r: '"No nos metas en tentación, mas líbranos del mal."' },
  93: { p: '¿Qué pedimos en la sexta petición?', r: 'Que Dios nos guarde de la tentación y nos libre de todo mal.' },
  94: { p: '¿Qué es la ley de Dios?', r: 'Son los diez mandamientos.' },
  95: { p: '¿Cuál es el primer mandamiento?', r: '"No tendrás dioses ajenos delante de mí."' },
  96: { p: '¿Qué nos enseña el primer mandamiento?', r: 'A adorar y servir a Dios solamente.' },
  97: { p: '¿Cuál es el segundo mandamiento?', r: '"No te harás imagen ni ninguna semejanza de las cosas del cielo ni de la tierra."' },
  98: { p: '¿Qué nos enseña el segundo mandamiento?', r: 'A adorar a Dios solo de la manera en que Él ha ordenado.' },
  99: { p: '¿Cuál es el tercer mandamiento?', r: '"No tomarás el nombre del Señor tu Dios en vano."' },
  100: { p: '¿Qué nos enseña el tercer mandamiento?', r: 'A reverenciar el nombre de Dios y todo lo que pertenece a Él.' },
  101: { p: '¿Cuál es el cuarto mandamiento?', r: '"Acuérdate del día de reposo para santificarlo."' },
  102: { p: '¿Qué nos enseña el cuarto mandamiento?', r: 'A guardar santo el día del Señor.' },
  103: { p: '¿Cuál es el día del Señor?', r: 'El primer día de la semana, el domingo, día de la resurrección de Cristo.' },
  104: { p: '¿Cuál es el quinto mandamiento?', r: '"Honra a tu padre y a tu madre."' },
  105: { p: '¿Qué nos enseña el quinto mandamiento?', r: 'A amar, honrar y obedecer a nuestros padres y a todos los que Dios puso en autoridad sobre nosotros.' },
  106: { p: '¿Cuál es el sexto mandamiento?', r: '"No matarás."' },
  107: { p: '¿Qué nos enseña el sexto mandamiento?', r: 'A no herir ni odiar a nadie, sino a amar y cuidar la vida.' },
  108: { p: '¿Cuál es el séptimo mandamiento?', r: '"No cometerás adulterio."' },
  109: { p: '¿Qué nos enseña el séptimo mandamiento?', r: 'A ser puros en pensamientos, palabras y acciones.' },
  110: { p: '¿Cuál es el octavo mandamiento?', r: '"No hurtarás."' },
  111: { p: '¿Qué nos enseña el octavo mandamiento?', r: 'A ser honestos y a no tomar lo que pertenece a otros.' },
  112: { p: '¿Cuál es el noveno mandamiento?', r: '"No hablarás contra tu prójimo falso testimonio."' },
  113: { p: '¿Qué nos enseña el noveno mandamiento?', r: 'A ser siempre verídicos y a no mentir ni engañar a nadie.' },
  114: { p: '¿Cuál es el décimo mandamiento?', r: '"No codiciarás la casa de tu prójimo, ni nada de lo que le pertenece."' },
  115: { p: '¿Qué nos enseña el décimo mandamiento?', r: 'A estar contentos con lo que tenemos y a no desear lo que es de otros.' },
  116: { p: '¿Puedes obedecer perfectamente los diez mandamientos?', r: 'No; ningún hombre puede guardarlos perfectamente.' },
  117: { p: '¿Qué mereces por haber quebrantado los mandamientos de Dios?', r: 'La ira y el castigo de Dios.' },
  118: { p: '¿Qué debes hacer cuando has pecado?', r: 'Arrepentirme, confesar mis pecados a Dios y pedir perdón en el nombre de Cristo.' },
  119: { p: '¿Perdonará Dios los pecados de los que se arrepienten?', r: 'Sí; "Si confesamos nuestros pecados, él es fiel y justo para perdonarnos."' },
  120: { p: '¿Cuál es el gran mandamiento de la ley?', r: 'Amarás al Señor tu Dios con todo tu corazón, con toda tu alma, con todas tus fuerzas y con toda tu mente.' },
  121: { p: '¿Cuál es el segundo mandamiento semejante a él?', r: 'Amarás a tu prójimo como a ti mismo.' },
  122: { p: '¿Quién es tu prójimo?', r: 'Todo ser humano, sea amigo o enemigo.' },
  123: { p: '¿Cómo podemos cumplir con la ley de Dios?', r: 'Solo por la gracia del Espíritu Santo, que obra en los que creen.' },
  124: { p: '¿Qué es la iglesia?', r: 'La congregación de todos los que creen en Cristo y son llamados por su Espíritu.' },
  125: { p: '¿Quiénes son miembros de la iglesia visible?', r: 'Todos los que profesan la fe en Cristo y sus hijos.' },
  126: { p: '¿Qué debemos hacer los domingos?', r: 'Adorar a Dios en la iglesia, descansar de nuestros trabajos y hacer bien a los demás.' },
  127: { p: '¿Qué sucede cuando escuchamos la Palabra de Dios predicada?', r: 'Dios habla a nuestras almas y el Espíritu Santo nos da fe.' },
  128: { p: '¿Debemos leer la Biblia en nuestra casa?', r: 'Sí; la familia debe leer, orar y alabar a Dios juntos cada día.' },
  129: { p: '¿Qué es la providencia de Dios?', r: 'El cuidado con que Dios gobierna todas las cosas para su gloria y el bien de su pueblo.' },
  130: { p: '¿Cuida Dios de todas las cosas?', r: 'Sí; ni aun un pajarillo cae a tierra sin la voluntad del Padre.' },
  131: { p: '¿Quiénes son los que Dios ha elegido para salvación?', r: 'Los que escogió en Cristo antes de la fundación del mundo, para ser santos delante de Él.' },
  132: { p: '¿Para qué debemos estudiar la Biblia?', r: 'Para conocer a Dios, aprender su voluntad y crecer en gracia.' },
  133: { p: '¿Qué es la fe salvadora?', r: 'Es confiar completamente en Cristo para ser salvo de los pecados.' },
  134: { p: '¿Pueden los niños ser salvos?', r: 'Sí; "dejad que los niños vengan a mí, pues de los tales es el reino de los cielos."' },
  135: { p: '¿Cómo deben los niños mostrar amor a Cristo?', r: 'Obedeciendo a sus padres, siendo verídicos y amando a todos.' },
  136: { p: '¿Qué es el Espíritu Santo?', r: 'La tercera persona de la Trinidad, tan plenamente Dios como el Padre y el Hijo.' },
  137: { p: '¿Qué obra el Espíritu Santo en nosotros?', r: 'Nos da vida nueva, nos ilumina, nos santifica y nos sella para el día de la redención.' },
  138: { p: '¿Qué es la santificación?', r: 'Es el proceso por el cual el Espíritu Santo nos hace cada vez más semejantes a Cristo.' },
  139: { p: '¿Qué significa que Dios es soberano?', r: 'Que Dios gobierna sobre todas las cosas según su santa voluntad.' },
  140: { p: '¿Qué quiere Dios que hagamos en este mundo?', r: 'Que le amemos, que obedezcamos sus mandamientos y que hagamos bien a todos.' },
  141: { p: '¿Debemos temer la muerte?', r: 'No; porque Cristo venció la muerte y el creyente tiene vida eterna.' },
  142: { p: '¿Qué esperamos al final de los tiempos?', r: 'La resurrección de los muertos y la vida en el cielo nuevo y la tierra nueva.' },
  143: { p: '¿Cómo debemos prepararnos para el día del juicio?', r: 'Creyendo en Cristo, viviendo en santidad y esperando su venida.' },
  144: { p: '¿Qué es la esperanza cristiana?', r: 'La certeza de que Cristo volverá, resucitará a los suyos y hará todas las cosas nuevas.' },
  145: { p: '¿Cuál es el resumen de todos los mandamientos?', r: 'Amar a Dios sobre todas las cosas y al prójimo como a mí mismo.' }
};
